#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load xterm settings
exec xrdb -merge ~/.Xresources &

# Run the network manager tray icon
exec nm-applet &

# Launch the screensaver daemon
exec xscreensaver -no-splash &

# Start the compositing manager for transparency in xterm
exec xcompmgr &

if [ "$HOSTNAME" == "Alex-ThinkPad" ]; then
    # System status bar
    exec conky -c /home/alex/.conkyrc | dzen2 -x 800 -y 0 -w 780 -ta r \
        -fn 'Inconsolata:size=12' &
    # System tray
    exec trayer --edge top --align right --height 19 --widthtype pixel \
        --width 20 --expand true --transparent true --alpha 0 --tint 0x111111 &

elif [ "$HOSTNAME" == "Alex-Latitude" ]; then
    # System status bar
    exec conky -c /home/alex/.conkyrc | dzen2 -x 700 -y 0 -w 560 -ta r \
        -fn 'Inconsolata:size=11' &
    # System tray
    exec trayer --edge top --align right --height 18 --widthtype pixel \
        --width 20 --expand true --transparent true --alpha 0 --tint 0x111111 &

elif [ "$HOSTNAME" == "Alex-Desktop" ]; then
    # System status bar
    exec conky -c /home/alex/.conkyrc | dzen2 -x 960 -y 0 -w 960 -ta r \
        -fn 'Inconsolata:size=12' &
    # Screen resolution
    exec xrandr --output HDMI-0 --mode 1920x1080 --primary --left-of DVI-0 \
        --output DVI-0 --mode 1280x1024 &

else
    # Write a file to the home folder with the unrecognised hostname
    echo "Hostname $HOSTNAME not recognised" > ~/xinitErr &
fi

# Set desktop wallpaper
exec sh ~/.fehbg &

# Run window manager selected by SLiM
exec xmonad
