#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load xterm settings
exec xrdb -merge ~/.Xresources &

# Run the network manager tray icon
exec nm-applet &

# Map caps lock to escape
exec setxkbmap -option caps:escape &

# Set desktop wallpaper
exec sh ~/.fehbg &

# Launch conky
exec conky -c /home/alex/.conkyrc | dzen2 -x 700 -y 0 -w 560 -ta r -fn 'Droid Sans Mono:size=10' &

# Run the system tray
exec trayer --edge top --align right --height 17 --widthtype pixel --width 20 --expand true --transparent true --alpha 0 --tint 0x111111 &

# Launch the screensaver daemon
exec xscreensaver -no-splash &

# Run XMonad
exec xmonad
