#!/bin/sh
#
# ~/.config/openbox/autostart
#
# This script runs when Openbox is started

# Start PyPanel
exec pypanel &

# Tray icons
exec cbatticon &
exec volumeicon &

# Restore the wallpaper
exec feh --bg-fill $HOME/Pictures/Gran_Canaria_by_ALF.jpg &
