#!/bin/sh

# Creates required symbolic links to the files in this repository, in the
# required locations. Run with 'sh links.sh'. This script requires that the git
# repo exist at '$HOME/.dotfiles/' and must be executed there.

# Command-line related things
stow console

# X.Org related things
stow xorg-common

# Window manager config files (uncomment just one - that one will be enabled)
stow i3
#stow xmonad
#stow openbox

# bin directory
stow bin

# Get the Luakit adblock list
mkdir -p $HOME/.local/share/luakit
wget --output-document=$HOME/.local/share/luakit/easylist.txt \
    https://easylist-downloads.adblockplus.org/easylist.txt
