set -g mouse on
setw -g mode-keys vi # vi movement in copy mode
set -s copy-command 'pbcopy' # copy/paste with system clipboard
bind-key -n M-3 send-keys '#' # fixes mac terminal misinterpreting Option-3 preventing typing '#'
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r y swap-pane -t '{left-of}'
bind -r u swap-pane -t '{down-of}'
bind -r i swap-pane -t '{up-of}'
bind -r o swap-pane -t '{right-of}'
set -g status-style "bg=default,fg=colour245"
set -g status-left " #S | #(whoami) "
set -g status-left-style "fg=colour81,bold"
set -g status-left-length 30
set -g status-right " %a %d %b %Y  %H:%M "
