#! /bin/sh

sxhkd &
polybar mybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      any

S_base03="#002b36"
S_base02="#073642"
S_base01="#586e75"
S_base00="#657b83"
S_base0="#839496"
S_base1="#93a1a1"
S_base2="#eee8d5"
S_base3="#fdf6e3"

bspc config normal_border_color   $S_base03
bspc config active border_color   $S_base03
bspc config focused_border_color  $S_base2
bspc config presel_feedback_color $S_base2

unset S_base03
unset S_base02
unset S_base01
unset S_base00
unset S_base0
unset S_base1
unset S_base2
unset S_base3
