#!/bin/sh
#
# ~/.config/openbox/autostart
#
# This script runs when Openbox is started

# Start PyPanel
exec lxpanel &

# Start batti (battery level indicator)
exec cbatticon &

# Start volumeicon (volume systray applet)
exec volumeicon &

# Restore the wallpaper
exec feh --bg-fill $HOME/Pictures/Gran_Canaria_by_ALF.jpg &
