#!/bin/sh
#
# ~/.config/openbox/autostart
#
# This script runs when Openbox is started

# Start PyPanel
exec pypanel &

# Start batti (battery level indicator)
exec batti &

# Start volumeicon (volume systray applet)
exec volumeicon &

# Restore the wallpaper
exec sh ~/.fehbg &
